name: Show Specific Environment Variable
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Show All Environment Variables
        run: env

      - name: Show GITHUB_SHA Path
        run: |
          echo "The value of JAVA_HOME is: $GITHUB_SHA"

